name: Sync with upstream

on:
  schedule:
    - cron: '0 * * * *'  # every hour
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false  # don't use default credentials

      - name: Set up Git
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      - name: Pull upstream changes
        run: |
          git remote add upstream https://github.com/ManOnTheMoonXIX/Custom-Language-With-Compiler.git
          git fetch upstream
          git checkout gui
          git merge upstream/gui --allow-unrelated-histories || true

      - name: Push changes to fork
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git remote set-url origin https://x-access-token:${TOKEN}@github.com/${{ github.repository }}
          git push origin gui
